app = 'portfolio-voice-ai'
primary_region = 'iad'  # Washington DC - close to US East Coast

[build]

[env]
  PORT = "8080"
  PYTHONUNBUFFERED = "1"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/"

[vm]
  cpu_kind = "shared"
  cpus = 2              # 2 CPUs for better performance
  memory_mb = 4096      # 4GB RAM - closer to LiveKit's 8GB recommendation

[[mounts]]
  source = "voice_ai_data"
  destination = "/data"
  initial_size = "10gb"

# Auto scaling configuration
[machine]
  auto_start = true
  auto_stop = false     # Keep running to avoid cold starts

# Process groups for better resource allocation
[processes]
  app = "python render_entrypoint.py"

# No restart section needed - handled by machine configuration

# Resource limits
[deploy]
  release_command = "echo 'Starting LiveKit Voice AI Agent'"
